### PR TITLE
Added configurable drupal_username_prefix

### PR DESCRIPTION
**Pull request by ralphvandenhoudt**

### CODE REVIEW

**Comment by pfaocle** [comment]
Thanks! Two things needed here:

* add a test for this functionality
* fix up code to meet PSR-2 standards (lns 56-58)

Will take a look at this as soon as I get some spare time - thanks again.

**Comment by ralphvandenhoudt** [comment]
Thnx, will do it soon

On 29/01/15 15:29, Paul Byrne wrote:
> Thanks! Two things needed here:
>
>   * add a test for this functionality
>   * fix up code to meet PSR-2 standards (lns 56-58)
>
> Will take a look at this as soon as I get some spare time - thanks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pfaocle/codeception-module-drupal-user-registry/pull/8#issuecomment-72033164>.
>

Met vriendelijke groet,

Ralph van den Houdt
(werkdagen: di, wo, do)

-- 
ezCompany BV
Tivolistraat 2
5017 HP  Tilburg
T +31 13 5322878
F +31 13 5322879
www.ezcompany.nl

**Comment by pfaocle** [comment]
I'm taking a look at the moment - I've fixed up PSR-2 and the current tests - replacing the constant for the prefix with a variable broke a test, but that part needed looking at anyway!

Will see if I get chance this evening to add a test myself for this and I'll merge. Many thanks!

**Comment by pfaocle** [comment]
Hi - I am closing this in favour of PR #9 

Feel free to contribute towards that PR but otherwise I'm happy to merge that shortly.

**Pull request closed without merging**
